name: Build and Tag
description: Properly tags your GitHub Action
runs:
  using: node12
  main: dist/index.js
branding:
  icon: heart
  color: red
inputs:
  setup:
    default: 'npm ci && npm run build --if-present'
    description: A command that runs before publishing the action to the release's tag.
