name: Build and Tag
description: Properly tags your GitHub Action
runs:
  using: node12
  main: dist/index.js
branding:
  icon: archive
  color: blue
inputs:
  setup:
    default: 'npm ci && npm run build --if-present'
    description: A command that runs before publishing the action to the release's tag.
  tag_name:
    description: The tag to update. If the workflow event is `release`, it will use the tag_name from the event payload.
